version: "3"

volumes:
  postgresql_data:
    driver: local
  api_data:
    driver: local

services:
  database:
    container_name: onboardexp_database
    restart: always
    image: postgres:12.3
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  api:
    container_name: onboardexp_api
    build:
      dockerfile: Dockerfile
      context: .
    image: harvest/onboardexp:latest
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      - "SPRING_PROFILES_ACTIVE=${ENV}"
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://database:${DATABASE_PORT}/${DATABASE_NAME}"
      - "SPRING_DATASOURCE_USERNAME=${DATABASE_USER}"
      - "SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}"
      - "SERVER_PORT=${APP_PORT}"
    volumes:
      - api_data:/usr/local/onboardexp
    depends_on:
      - "database"
    links:
      - "database:database"
