ALTER TABLE tbfile
ADD description CHARACTER VARYING;

CREATE TABLE public.tbanswer_question (
  idanswer BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  answer VARCHAR(255),
  idquestion BIGINT,
  is_correct BOOLEAN,
  CONSTRAINT pk_tbanswer_question PRIMARY KEY (idanswer)
);

ALTER TABLE public.tbanswer_question ADD CONSTRAINT FK_TBANSWERQUESTION_ON_ID_QUESTION FOREIGN KEY (idquestion) REFERENCES public.tbquestion (idquestion);
